import type { Workspace } from "./types";

export const seedWorkspace: Workspace = {
  currentDesignerId: "d-jess",
  designers: [
    { id: "d-jess", name: "Jess Duguid", initials: "JD", color: "#7c5cff", pin: "1001" },
    { id: "d-oliver", name: "Oliver Braun", initials: "OB", color: "#ff7a59", pin: "1002" },
    { id: "d-ben", name: "Ben Marin", initials: "BM", color: "#22b8a6", pin: "1003" },
    { id: "d-karen", name: "Karen De Lara", initials: "KD", color: "#f2c94c", pin: "1004" },
    { id: "d-attreyee", name: "Attreyee Ghosh", initials: "AG", color: "#3b82f6", pin: "1005" },
    { id: "d-rachel", name: "Rachel Tse", initials: "RT", color: "#ec4899", pin: "1006" },
    { id: "d-danielle", name: "Danielle Clark", initials: "DC", color: "#10b981", pin: "1007" },
    { id: "d-heather", name: "Heather Cipullo", initials: "HC", color: "#f97316", pin: "1008" },
    { id: "d-patrice", name: "Patrice Roarke", initials: "PR", color: "#8b5cf6", pin: "1009" },
  ],
  projects: [
    {
      id: "p-001",
      title: "CargoWise Q3 Launch Banner",
      overview: "Hero banner set for the Q3 product launch landing page.",
      client: "CargoWise — Marketing",
      brand: "CargoWise",
      productArea: "Web",
      briefUrl: "https://example.com/briefs/cw-q3-launch.pdf",
      dueDate: "2026-06-04",
      priority: "Urgent",
      assigneeId: "d-jess",
      milestones: [
        { id: "m1", label: "Concept review", done: true },
        { id: "m2", label: "Stakeholder sign-off", done: false },
        { id: "m3", label: "Final export", done: false },
      ],
      comments: [
        {
          id: "c1",
          author: "Sarah Knight",
          text: "Please lean into the new gradient palette.",
          createdAt: "2026-05-20T09:14:00Z",
        },
      ],
      createdAt: "2026-05-18T10:00:00Z",
      source: "manual",
    },
    {
      id: "p-002",
      title: "Customs Webinar Social Pack",
      overview: "LinkedIn + Twitter social tiles for the customs webinar series.",
      client: "Customs Team",
      brand: "WiseTech Global",
      productArea: "Social",
      briefUrl: "https://example.com/briefs/customs-webinar.pdf",
      dueDate: "2026-05-30",
      priority: "High",
      assigneeId: "d-jess",
      milestones: [
        { id: "m1", label: "First drafts", done: true },
        { id: "m2", label: "Copy review", done: false },
      ],
      comments: [],
      createdAt: "2026-05-15T08:00:00Z",
      source: "manual",
    },
    {
      id: "p-101",
      title: "Compliance Whitepaper Layout",
      overview: "20-page whitepaper interior design with diagrams.",
      client: "Compliance",
      brand: "WiseTech Global",
      productArea: "Print",
      briefUrl: "https://example.com/briefs/whitepaper.pdf",
      dueDate: "2026-06-20",
      priority: "High",
      assigneeId: "d-oliver",
      milestones: [],
      comments: [],
      createdAt: "2026-05-12T08:00:00Z",
      source: "manual",
    },
    {
      id: "p-102",
      title: "Trade Show Booth Graphics",
      overview: "Large-format graphics for the June trade show booth.",
      client: "Events",
      brand: "CargoWise",
      productArea: "Event",
      briefUrl: "https://example.com/briefs/booth.pdf",
      dueDate: "2026-06-10",
      priority: "Urgent",
      assigneeId: "d-ben",
      milestones: [],
      comments: [],
      createdAt: "2026-05-08T08:00:00Z",
      source: "manual",
    },
    {
      id: "p-201",
      title: "Onboarding Email Templates",
      overview: "Refresh of the customer onboarding email series.",
      client: "Customer Success",
      brand: "WiseTech Global",
      productArea: "Email",
      briefUrl: "https://example.com/briefs/email-onboarding.pdf",
      dueDate: "2026-06-15",
      priority: "Normal",
      assigneeId: "d-karen",
      milestones: [],
      comments: [],
      createdAt: "2026-05-14T08:00:00Z",
      source: "manual",
    },
    {
      id: "p-301",
      title: "Mobile App Icon Refresh",
      overview: "Updated iOS / Android icon set for the customer portal.",
      client: "Product",
      brand: "WiseTech Global",
      productArea: "Mobile",
      briefUrl: "https://example.com/briefs/icons.pdf",
      dueDate: "2026-07-01",
      priority: "Low",
      assigneeId: "d-rachel",
      milestones: [],
      comments: [],
      createdAt: "2026-05-16T08:00:00Z",
      source: "manual",
    },
    {
      id: "p-401",
      title: "Annual Report 2026 Cover",
      overview: "Cover artwork concepts for the 2026 annual report.",
      client: "Investor Relations",
      brand: "WiseTech Global",
      productArea: "Print",
      briefUrl: "https://example.com/briefs/annual-report.pdf",
      dueDate: "2026-07-12",
      priority: "Normal",
      assigneeId: "d-attreyee",
      milestones: [],
      comments: [],
      createdAt: "2026-05-10T08:00:00Z",
      source: "manual",
    },
    {
      id: "p-501",
      title: "Sales Deck Refresh",
      overview: "Updated master sales deck template — 40+ slides.",
      client: "Sales Enablement",
      brand: "WiseTech Global",
      productArea: "Presentation",
      briefUrl: "https://example.com/briefs/sales-deck.pdf",
      dueDate: "2026-06-25",
      priority: "High",
      assigneeId: "d-danielle",
      milestones: [],
      comments: [],
      createdAt: "2026-05-17T08:00:00Z",
      source: "manual",
    },
    {
      id: "p-601",
      title: "Brand Refresh Style Guide",
      overview: "Updated style guide with new typography and colour tokens.",
      client: "Brand",
      brand: "WiseTech Global",
      productArea: "Brand",
      briefUrl: "https://example.com/briefs/brand-guide.pdf",
      dueDate: "2026-08-01",
      priority: "Normal",
      assigneeId: "d-heather",
      milestones: [],
      comments: [],
      createdAt: "2026-05-09T08:00:00Z",
      source: "manual",
    },
    {
      id: "p-701",
      title: "Partner Portal Illustrations",
      overview: "Custom illustration set for the partner portal empty states.",
      client: "Partners Team",
      brand: "WiseTech Global",
      productArea: "Illustration",
      briefUrl: "https://example.com/briefs/partner-illos.pdf",
      dueDate: "2026-06-30",
      priority: "Normal",
      assigneeId: "d-patrice",
      milestones: [],
      comments: [],
      createdAt: "2026-05-11T08:00:00Z",
      source: "manual",
    },
  ],
};
